# Mongodb configuration
spring.data.mongodb.uri = ${MONGO_DB_URL}
management.endpoint.health.show-details=always
management.health.mongo.enabled=false
management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=health


#Email Configuration
spring.mail.host=${EMAIL_HOST}
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=${EMAIL_FROM}

# Application info
app.base.url=http://localhost:8080

# Cloudinary information
cloudinary.cloud-name=${CLOUDINARY_NAME}
cloudinary.api-key=${CLOUDINARY_KEY}
cloudinary.api-secret=${CLOUDINARY_SECRET_KEY}
cloudinary.enabled=true

# JWT Configuration
jwt.secret=welome-to-resumate-your-only-destination-for-ats-friendly-resume-building-as-we-say-BEAT-THE-ATS
jwt.expiration=604800000

# Razorpay Configuration
razorpay.key.id=${RAZORPAY_KEY}
razorpay.key.secret=${RAZORPAY_SECRET_KEY}

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# Application Home Page URL
app.home.url = ${APPLICATION_URL}